checks:
    php: true

build:
    environment:
        php:
            version: 7.1
        mysql: 5.7
        variables:
            APP_ENV: 'test'
            DATABASE_URL: 'mysql://root@localhost:3306/mydatabase'

    project_setup:
        before:
            - mysql -e "CREATE DATABASE mydatabase"
    tests:
        override:
            -
                command: php bin/phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
