build:
    environment:
        docker: true
    project_setup:
        - cp .env.dist .env
        - cp docker-compose.override.yml.dist docker-compose.override.yml
        - docker-compose up -d
        - docker-compose exec web composer install
        - docker-compose exec web php bin/console doctrine:database:drop --force
        - docker-compose exec web php bin/console doctrine:database:create
        - docker-compose exec web php bin/console doctrine:schema:update --force
        - docker-compose exec web php bin/console doctrine:schema:validate
        - docker-compose exec web php bin/console doctrine:fixtures:load --no-interaction
    tests:
        override:
            -
                command:  docker-compose exec web php bin/phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
