sudo: required

language: php

services:
    - docker

before_install:
    - cp .env.dist .env
    - docker-compose up -d
    - docker-compose exec web composer install --no-interaction

script:
    - docker-compose exec web php bin/phpunit --coverage-clover build/coverage/xml

after_script:
    - php vendor/bin/codacycoverage clover build/coverage/xml
