sudo: required

services:
    - docker

before_install:
    - cp .env.test.dist .env
    - docker-compose up -d
    - docker-compose exec web composer install
    - docker-compose exec web php bin/console doctrine:schema:update --force

script:
    - docker-compose exec php bin/console doctrine:schema:validate
    - docker-compose exec php bin/console about
    - docker-compose exec phpunit
