language: php
php:
  - '7.1'
  - nightly

env:
  - SYMFONY_ENV=test

matrix:
  allow_failures:
    - php: nightly

script:
  - composer install
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:schema:validate
  - php bin/console about
