sudo: required

services:
    - docker

before_install:
    - cp .env.dist .env
    - docker-compose pull
    - docker-compose run --rm -e SYMFONY_ENV=test web composer install --no-interaction
    - docker-compose run --rm -e SYMFONY_ENV=test web php bin/console doctrine:schema:update --force

script:
    - docker-compose run --rm -e SYMFONY_ENV=test web php bin/console doctrine:schema:validate --skip-sync
    - docker-compose run --rm -e SYMFONY_ENV=test web php bin/console about
    - docker-compose run --rm -e SYMFONY_ENV=test web vendor/bin/phpunit
