sudo: required

services:
    - docker

before_install:
    - cp .env.dist .env
    - cp docker-compose.override.yml.dist docker-compose.override.yml
    - docker-compose up -d
    - docker-compose exec web composer install --no-interaction

script:
    - docker-compose exec web php bin/phpunit --coverage-clover coverage.xml

after_script:
    - docker-compose exec web php vendor/bin/codacycoverage clover coverage.xml
