sudo: required

services:
    - docker

before_install:
    - cp .env.test.dist .env
    - docker-compose up -d
    - docker-compose exec web composer install --no-interaction

script:
    - docker-compose exec php bin/console about
    - docker-compose exec phpunit
