language: php
php:
  - '7.0'
  - '7.1'
  - nightly

env:
  - SYMFONY_ENV=prod

matrix:
  allow_failures:
    - php: nightly

script:
  - composer install
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:schema:validate
  - php bin/console security:check
  - php bin/console doctrine:ensure-production-settings
  - php bin/console about
