sudo: required

language: php

php:
    - nightly

services:
    - docker

before_install:
    - cp .env.dist .env
    - cp docker-compose.override.yml.dist docker-compose.override.yml
    - docker-compose up -d
    - docker-compose exec web composer install --no-interaction
    - docker-compose exec web php bin/console doctrine:database:create
    - docker-compose exec web php bin/console doctrine:schema:update --force
    - docker-compose exec web php bin/console doctrine:schema:validate

script:
    - docker-compose exec web php bin/phpunit --coverage-clover build/coverage/xml

after_script:
    - php vendor/bin/codacycoverage clover build/coverage/xml
