version: '3'

services:

  web:
      image: webdevops/php-apache:7.1
      volumes:
          - ./:/app
      working_dir: /app
      env_file: .env
      ports:
          - "80:80"
      environment:
          WEB_DOCUMENT_ROOT: /app/web
          WEB_DOCUMENT_INDEX: app.php
          PHP_DATE_TIMEZONE: "Europe/Paris"
          PHP_DISPLAY_ERRORS: 1
