version: "3"

services:

  web:
      image: webdevops/php-nginx-dev:7.1
      volumes:
          - ./:/app
      working_dir: /app
      env_file: .env
      depends_on:
          - database
      environment:
          WEB_DOCUMENT_ROOT: /app/public
          WEB_DOCUMENT_INDEX: index.php
          PHP_DATE_TIMEZONE: "Europe/Paris"
          PHP_DISPLAY_ERRORS: 1

  database:
      image: percona:5.7
      volumes:
          - ./docker/database:/etc/mysql/conf.d
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydatabase

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
          - database
      environment:
          MYSQL_ROOT_PASSWORD: root
          PMA_HOST: database
