index:
    path: /
    controller: App\Controller\DefaultController::index

admin:
    path: /admin
    controller: App\Controller\AdminController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
