index:
    path: /
    controller: App\Controller\DefaultController::index

admin:
    path: /admin
    controller: App\Controller\DefaultController::admin

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
